### ISSUE TITLE
Do not require Enum as a Event or State generic argument

### ISSUE THREAD

**Issue by TarasMazepa** [vitkhudenko/session_tracker#4]
Right now it is required by framework. But people can choose to use something else `@IntDef` for example.

**Comment by vitkhudenko** [comment]
In the epoch of RxJava ubiquity preferring @IntDef over enums appears as over-optimization. :)

**Comment by vitkhudenko** [comment]
I should add that forcing `Event` and `State` to be enums is enforced by the underlying finite state machine library. On the other hand, it is not bad at all - it brings some guarantees, semantic benefits and better logs readability.

**Comment by TarasMazepa** [comment]
> In the epoch of RxJava ubiquity preferring @IntDef over enums appears as over-optimization. :)

Yeah, even proguard and D8 (or R8) already learned how to simplify them into ints during compilation.

> I should add that forcing Event and State to be enums is enforced by the underlying finite state machine library. 

I noticed that before commenting on this.

> On the other hand, it is not bad at all - it brings some guarantees, semantic benefits and better logs readability.

Guarantees - true. But from my POV users should be able to make that decision by themselves.

One another use case:
People can prever Sealed classes over Enums, which also will not be supported by current implementation.

**Comment by vitkhudenko** [comment]
The whole idea of a state machine is based on immutability of events and states. Enums and primitives suit best. However primitives, desipite being a bit more performance effective than enums, are not best in terms of semantics/readability (otherwise we would still use primitives).

Unfortunately, Kotlin sealed classes are not guaranteed to be immutable.

Technically I could allow both enums AND primitives, but for that I would have to expand generic types for events/events from `<Event : Enum<Event>>` to `<Event : Any>`, which would be misleading, because state machine would still validate types for being either enum or primitive and throw an exception to avoid misconfig.

Having said that, I prefer to stay with enums only.
